import React from 'react';
import { Shield, Lock, Eye, AlertTriangle } from 'lucide-react';

const PrivacyPolicy = () => {
  return (
    <div className="space-y-8 animate-in fade-in duration-500 h-full pb-20">
      <div className="flex items-center space-x-3 mb-6">
        <div className="p-3 bg-brand-primary/20 rounded-xl text-brand-primary">
          <Shield size={28} />
        </div>
        <div>
          <h1 className="text-3xl font-bold">Privacy Policy</h1>
          <p className="text-brand-secondary">Last Updated: October 2026</p>
        </div>
      </div>

      <div className="glass-panel p-8 rounded-3xl mx-auto space-y-8 text-gray-300 leading-relaxed max-w-4xl">
        
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white flex items-center space-x-2">
            <Eye className="text-brand-primary" size={24} />
            <span>1. Information We Collect</span>
          </h2>
          <p>
            At SeeMe Pro, your privacy is our priority. We collect minimal information to provide our services:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Media Data:</strong> Any video, audio, or image files you upload are processed securely in real-time or via secure temporary processing servers. We <strong>do not store</strong> your personal media files after the analysis is complete.</li>
            <li><strong>Anonymous Usage Data:</strong> We generate an anonymous Device ID to track your gamification limits (e.g., how many free attempts you have left). No personally identifiable information (PII) like your name or email is required to use the core features.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white flex items-center space-x-2">
            <Lock className="text-brand-ai" size={24} />
            <span>2. Google AdSense & Cookies</span>
          </h2>
          <p>
            We use Google AdSense to display rewarded advertisements. Google AdSense uses cookies to serve ads based on a user's prior visits to our website or other websites.
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Google's use of advertising cookies enables it and its partners to serve ads to you based on your visit to SeeMe Pro and/or other sites on the Internet.</li>
            <li>You may opt out of personalized advertising by visiting Google's <a href="https://myadcenter.google.com/" target="_blank" rel="noopener noreferrer" className="text-brand-primary hover:underline">Ads Settings</a>.</li>
            <li>We use local storage mechanisms to track your reward progress (e.g., ensuring you receive your analysis attempt after watching a rewarded video).</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white flex items-center space-x-2">
            <AlertTriangle className="text-orange-500" size={24} />
            <span>3. Entertainment Purpose Only</span>
          </h2>
          <p>
            SeeMe Pro utilizes artificial intelligence, including voice and facial recognition, to provide behavioral analysis. 
            <strong> These results are generated for entertainment and self-reflection purposes only.</strong>
          </p>
          <p>
            The analysis provided by SeeMe Pro is not scientifically validated and must not be used for legal, medical, psychological, diagnostic, or critical decision-making purposes. We disclaim any liability for actions taken based on the results generated by this application.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">4. Data Security</h2>
          <p>
            We implement industry-standard security measures (including Row Level Security databases) to ensure that your gamification state and anonymous data are strictly isolated. You only have access to your own data instance.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">5. Changes to This Policy</h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
          </p>
        </section>

        <div className="mt-12 pt-8 border-t border-gray-800 text-sm text-center text-brand-secondary">
          <p>If you have any questions about this Privacy Policy, please contact us through our official channels.</p>
        </div>

      </div>
    </div>
  );
};

export default PrivacyPolicy;
